# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('gpa', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
